### ISSUE TITLE
0.2 and 0.3 are broken on Python 3

### ISSUE THREAD

**Issue by techtonik** [techtonik/pypack#4]
`0.1` was ok - https://travis-ci.org/techtonik/python-patch/jobs/160276595
`0.3` is not - https://travis-ci.org/techtonik/python-patch/jobs/577891157#L186 

```
Traceback (most recent call last):
  File "/opt/python/3.4.8/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/python/3.4.8/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/travis/virtualenv/python3.4.8/lib/python3.4/site-packages/pypack.py", line 202, in <module>
    main()
  File "/home/travis/virtualenv/python3.4.8/lib/python3.4/site-packages/pypack.py", line 185, in main
    if not get_main(modpath):
  File "/home/travis/virtualenv/python3.4.8/lib/python3.4/site-packages/pypack.py", line 59, in get_main
    if line.startswith('def main('):
TypeError: startswith first arg must be bytes or a tuple of bytes, not str
The command "python -m pypack patch.py" exited with 1.
```

**Comment by techtonik** [comment]
The offending commit was a fix for #3.
